### PR TITLE
Merge pull request #30 from Zocom-LIA/feature/frontend

### PR DESCRIPTION
**Pull request by majmalgot**
Update HTML file with necessary changes for frontend feature

### CODE REVIEW

**Comment by majmalgot** [comment]
This is not a major change or update. This is for testing the PR

**Review by EiriniSkor — APPROVED** [review]

**Review by vinisha77 — APPROVED** [review]
Hi @majmalgot Looks good to me

**Review by EELMMAD — APPROVED** [review]
I approved the changes

**Comment by SwethaKey** [comment]
I approved

**Pull request merged**
